# Generated by Django 3.2.4 on 2021-06-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0006_alter_proteindomain_protein_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Pfam',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domains',
        ),
        migrations.AddField(
            model_name='protein',
            name='pfams',
            field=models.ManyToManyField(through='restAPI.ProteinDomain', to='restAPI.Pfam'),
        ),
        migrations.AlterField(
            model_name='proteindomain',
            name='protein_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='restAPI.protein'),
        ),
    ]
