# Generated by Django 3.2.4 on 2021-06-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=13)),
                ('domain_description', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('taxa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.CharField(max_length=1)),
                ('genus', models.CharField(max_length=127)),
                ('species', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('sequence', models.CharField(max_length=35991)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('description', models.CharField(max_length=147)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restAPI.domain')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restAPI.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='restAPI.ProteinDomain', to='restAPI.Domain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restAPI.organism'),
        ),
    ]
