# Generated by Django 3.2.4 on 2021-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_proteindomain_unique_domain_within_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_id',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
