# Generated by Django 3.2.4 on 2021-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0009_auto_20210629_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.CharField(blank=True, max_length=35991, null=True),
        ),
    ]
